# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
# ignore all warnings from all pods
inhibit_all_warnings!


target 'LaoTzuPDF' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LaoTzuPDF

pod 'R.swift'
pod 'SwiftyBeaver'
pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"
pod 'IQKeyboardManagerSwift'
#pod 'Swifter'
pod 'Mummy'


end
