//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.image` struct is generated, and contains static references to 2 images.
  struct image {
    /// Image `edit-annotations`.
    static let editAnnotations = Rswift.ImageResource(bundle: R.hostingBundle, name: "edit-annotations")
    /// Image `foxIcon`.
    static let foxIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "foxIcon")
    
    /// `UIImage(named: "edit-annotations", bundle: ..., traitCollection: ...)`
    static func editAnnotations(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.editAnnotations, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "foxIcon", bundle: ..., traitCollection: ...)`
    static func foxIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.foxIcon, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 1 nibs.
  struct nib {
    /// Nib `WatermarkConfigurationViewController`.
    static let watermarkConfigurationViewController = _R.nib._WatermarkConfigurationViewController()
    
    /// `UINib(name: "WatermarkConfigurationViewController", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.watermarkConfigurationViewController) instead")
    static func watermarkConfigurationViewController(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.watermarkConfigurationViewController)
    }
    
    static func watermarkConfigurationViewController(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> WaterConfigurationView? {
      return R.nib.watermarkConfigurationViewController.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? WaterConfigurationView
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    struct _WatermarkConfigurationViewController: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "WatermarkConfigurationViewController"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> WaterConfigurationView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? WaterConfigurationView
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try launchScreen.validate()
      try main.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = DocumentBrowserViewController
      
      let bundle = R.hostingBundle
      let documentBrowserViewController = StoryboardViewControllerResource<DocumentBrowserViewController>(identifier: "DocumentBrowserViewController")
      let name = "Main"
      let navigationController = StoryboardViewControllerResource<UIKit.UINavigationController>(identifier: "NavigationController")
      
      func documentBrowserViewController(_: Void = ()) -> DocumentBrowserViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: documentBrowserViewController)
      }
      
      func navigationController(_: Void = ()) -> UIKit.UINavigationController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: navigationController)
      }
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
        if _R.storyboard.main().documentBrowserViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'documentBrowserViewController' could not be loaded from storyboard 'Main' as 'DocumentBrowserViewController'.") }
        if _R.storyboard.main().navigationController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'navigationController' could not be loaded from storyboard 'Main' as 'UIKit.UINavigationController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
